Typo - Issue #104
rbicelli/pfsense-zabbix-template pull request #108
Opened 2022-02-16 09:56 UTC by GuillaumeHullin

(sorry, I thought I included it in yesterday PR)

2022-09-13 20:01 UTC, rbicelli requested changes
Please leave the top lines with buy me a coffeee badge as they are.

2022-09-13 20:08 UTC, GuillaumeHullin commented
Sorry, I went a bit quick on the copy/paste from my repo

2022-09-13 20:14 UTC, rbicelli reviewed
The main thing is if you want to merge to the main repo you need to keep the original references and not to rebrand the template.

2022-09-13 20:14 UTC, rbicelli commented on README.md
> -curl --create-dirs -o /root/scripts/pfsense_zbx.php https://raw.githubusercontent.com/rbicelli/pfsense-zabbix-template/master/pfsense_zbx.php
Please leave my repository as default

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_ipsec.xml
> +https://github.com/Futur-Tech/futur-tech-zabbix-pfsense</description>
Please leave reference to original repository.
You can maintain your own branch but for merging to main repo it is mandatory to leave links pointing there

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_ovpn_user.xml
> +            <name>Templates/Futur-Tech/Applications</name>
Please leave reference to original category.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_ovpn_user.xml
> +            <name>Template Futur-Tech App pfSense Active OpenVPN Server User Auth</name>
Please leave reference to original category.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_ovpn_user.xml
> +https://github.com/Futur-Tech/futur-tech-zabbix-pfsense</description>
Please leave reference to original maintainer.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_ovpn_user.xml
> +                    <name>Templates/Futur-Tech/Applications</name>
Please leave reference to original category.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_speedtest.xml
> +            <name>Templates/Futur-Tech/Modules pfSense</name>
Please leave reference to original category.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_speedtest.xml
> +            <name>Template Futur-Tech App pfSense Active Speedtest</name>
Please leave reference to original category.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_speedtest.xml
> +https://github.com/Futur-Tech/futur-tech-zabbix-pfsense</description>
Please leave reference to original maintainer.

2022-09-13 20:14 UTC, rbicelli commented on template_pfsense_active_speedtest.xml
> +                    <name>Templates/Futur-Tech/Modules pfSense</name>
Please leave reference to original category.

2022-09-13 20:23 UTC, GuillaumeHullin commented
Yes, I fully understand.
I rebranded in my repo in order to fit with my other repos and my Zabbix setup.

I tried to make a middle forked-repo between yours and my main to avoid  pushing my branding changes but I clearly mixed up myself. 

Really sorry for the inconvenience. 

I'm gonna review everything and ask for review once it's done.

2022-09-14 09:45 UTC, GuillaumeHullin commented
I think I found why my PR changed more than what I planned on. When I created this PR almost a year ago, I should have created a separate branche in my fork... because all the changes with Futur-Tech branding that cames months after changed the content of this PR.
Lesson learned.

2022-09-14 19:36 UTC, rbicelli approved these changes

2022-11-07 22:07 UTC, merged